default: &default
  adapter: mysql2
  encoding: utf8mb4
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: root
  password: Admin123
  host: db  

development:
  <<: *default
  database: one_drink_db

test:
  <<: *default
  database: one_drink_test

production:
  <<: *default
  database: <%= ENV["MYSQL_PRD_DATABASE"] %>
  username: <%= ENV["MYSQL_USERNAME"] %>
  password: <%= ENV["MYSQL_PASSWORD"] %>
  host: <%= ENV["MYSQL_HOST"] %>
